# Python Flask CI/CD Pipeline
#
# This pipeline demonstrates a complete CI/CD workflow:
# 1. Build and test on Harness Cloud
# 2. Build Docker image and push to ECR
# 3. Deploy to Kubernetes dev environment
# 4. Manual approval gate
# 5. Deploy to Kubernetes production
#
# Prerequisites:
# - github_connector: GitHub connector for source code
# - aws_connector: AWS connector for ECR access
# - flask_app_service: Harness service definition
# - dev/prod: Environment definitions
# - k8s_dev_cluster/k8s_prod_cluster: Infrastructure definitions
# - slack_webhook: Secret for Slack notifications

pipeline:
  identifier: python_flask_cicd
  name: Python Flask CI/CD Pipeline
  projectIdentifier: my_project
  orgIdentifier: my_org
  tags:
    team: backend
    language: python
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: flask-app
        build:
          type: branch
          spec:
            branch: <+trigger.branch>
  stages:
    # Stage 1: Build and Test
    - stage:
        identifier: build_and_test
        name: Build and Test
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: install_deps
                  name: Install Dependencies
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                      pip install -r requirements-dev.txt
              - parallel:
                  - step:
                      identifier: lint
                      name: Lint
                      type: Run
                      spec:
                        shell: Bash
                        command: |
                          pip install flake8 black
                          flake8 src/
                          black --check src/
                  - step:
                      identifier: unit_tests
                      name: Unit Tests
                      type: Run
                      spec:
                        shell: Bash
                        command: |
                          pip install pytest pytest-cov
                          pytest tests/ --cov=src --cov-report=xml --junitxml=junit.xml
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - "junit.xml"
              - step:
                  identifier: build_push_ecr
                  name: Build and Push to ECR
                  type: BuildAndPushECR
                  spec:
                    connectorRef: aws_connector
                    region: us-east-1
                    account: "123456789012"
                    imageName: flask-app
                    tags:
                      - <+pipeline.sequenceId>
                      - <+codebase.commitSha>
                      - latest
                    dockerfile: Dockerfile
                    context: .
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1000m
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure

    # Stage 2: Deploy to Dev
    - stage:
        identifier: deploy_dev
        name: Deploy to Dev
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: flask_app_service
          environment:
            environmentRef: dev
            infrastructureDefinitions:
              - identifier: k8s_dev_cluster
          execution:
            steps:
              - step:
                  identifier: rollout_dev
                  name: Rollout Deployment
                  type: K8sRollingDeploy
                  spec:
                    skipDryRun: false
                  timeout: 10m
              - step:
                  identifier: health_check
                  name: Health Check
                  type: Http
                  spec:
                    url: https://dev.myapp.com/health
                    method: GET
                    assertion: <+httpResponseCode> == 200
                  timeout: 2m
            rollbackSteps:
              - step:
                  identifier: rollback_dev
                  name: Rollback
                  type: K8sRollingRollback
                  spec: {}
                  timeout: 10m
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback

    # Stage 3: Production Approval
    - stage:
        identifier: prod_approval
        name: Production Approval
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  identifier: approve_prod
                  name: Approve Production Deployment
                  type: HarnessApproval
                  spec:
                    approvalMessage: |
                      Please review and approve deployment to production.

                      Build: <+pipeline.sequenceId>
                      Commit: <+codebase.commitSha>
                      Branch: <+codebase.branch>
                    approvers:
                      userGroups:
                        - production_approvers
                      minimumCount: 1
                    includePipelineExecutionHistory: true
                  timeout: 24h

    # Stage 4: Deploy to Production
    - stage:
        identifier: deploy_prod
        name: Deploy to Production
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: flask_app_service
          environment:
            environmentRef: prod
            infrastructureDefinitions:
              - identifier: k8s_prod_cluster
          execution:
            steps:
              - step:
                  identifier: rollout_prod
                  name: Rollout Deployment
                  type: K8sRollingDeploy
                  spec:
                    skipDryRun: false
                  timeout: 15m
              - step:
                  identifier: health_check_prod
                  name: Health Check
                  type: Http
                  spec:
                    url: https://myapp.com/health
                    method: GET
                    assertion: <+httpResponseCode> == 200
                  timeout: 2m
              - step:
                  identifier: notify_success
                  name: Notify Success
                  type: Http
                  spec:
                    url: <+secrets.getValue("slack_webhook")>
                    method: POST
                    headers:
                      - key: Content-Type
                        value: application/json
                    body: |
                      {
                        "text": "Flask App deployed to production successfully! Build: <+pipeline.sequenceId>"
                      }
                  timeout: 30s
            rollbackSteps:
              - step:
                  identifier: rollback_prod
                  name: Rollback
                  type: K8sRollingRollback
                  spec: {}
                  timeout: 10m
              - step:
                  identifier: notify_rollback
                  name: Notify Rollback
                  type: Http
                  spec:
                    url: <+secrets.getValue("slack_webhook")>
                    method: POST
                    headers:
                      - key: Content-Type
                        value: application/json
                    body: |
                      {
                        "text": "Production deployment rolled back! Build: <+pipeline.sequenceId>"
                      }
                  timeout: 30s
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback

  notificationRules:
    - name: Pipeline Failure Notification
      enabled: true
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Slack
        spec:
          webhookUrl: <+secrets.getValue("slack_webhook")>
    - name: Pipeline Success Notification
      enabled: true
      pipelineEvents:
        - type: PipelineSuccess
      notificationMethod:
        type: Email
        spec:
          recipients:
            - team@example.com
