# GitHub CI/CD Triggers
#
# A complete set of triggers for a standard CI/CD workflow:
# 1. PR Trigger - Runs CI on pull requests
# 2. Push Trigger - Deploys to staging on merge to main
# 3. Release Trigger - Deploys to production on release publish
#
# Prerequisites:
# - github_connector: GitHub connector with webhook access
# - ci_pipeline: CI pipeline for running tests
# - deploy_pipeline: Deployment pipeline with environment variable
#
# Usage:
#   Apply each trigger separately in Harness or use the API to create them.

---
# Trigger 1: Pull Request CI
# Runs the CI pipeline when PRs are opened, synchronized, or reopened
# Automatically aborts previous runs when new commits are pushed

trigger:
  identifier: github_pr_ci_trigger
  name: GitHub PR CI Trigger
  orgIdentifier: my_org
  projectIdentifier: my_project
  pipelineIdentifier: ci_pipeline
  description: "Run CI checks on pull requests targeting main or develop branches"
  enabled: true
  tags:
    type: ci
    event: pull_request
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: github_connector
          repoName: my-org/my-app
          autoAbortPreviousExecutions: true
          actions:
            - Open
            - Synchronize
            - Reopen
            - ReadyForReview
          payloadConditions:
            - key: targetBranch
              operator: In
              value: main, develop
            - key: sourceBranch
              operator: Regex
              value: ^(feature|bugfix|hotfix)/.*
          headerConditions: []
          jexlCondition: "<+trigger.payload.pull_request.draft> == false"
  inputYaml: |
    pipeline:
      variables:
        - name: pr_number
          type: String
          value: <+trigger.prNumber>
        - name: pr_title
          type: String
          value: <+trigger.prTitle>
        - name: source_branch
          type: String
          value: <+trigger.sourceBranch>
        - name: target_branch
          type: String
          value: <+trigger.targetBranch>
        - name: commit_sha
          type: String
          value: <+trigger.commitSha>

---
# Trigger 2: Main Branch Push - Deploy to Staging
# Deploys to staging environment when code is merged to main

trigger:
  identifier: staging_deploy_trigger
  name: Staging Deploy Trigger
  orgIdentifier: my_org
  projectIdentifier: my_project
  pipelineIdentifier: deploy_pipeline
  description: "Deploy to staging when code is pushed to main branch"
  enabled: true
  tags:
    type: cd
    environment: staging
    event: push
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: github_connector
          repoName: my-org/my-app
          autoAbortPreviousExecutions: false
          payloadConditions:
            - key: targetBranch
              operator: Equals
              value: main
            - key: <+trigger.payload.head_commit.message>
              operator: DoesNotContain
              value: "[skip ci]"
          headerConditions: []
          jexlCondition: ""
  inputYaml: |
    pipeline:
      variables:
        - name: environment
          type: String
          value: staging
        - name: commit_sha
          type: String
          value: <+trigger.commitSha>
        - name: commit_message
          type: String
          value: <+trigger.payload.head_commit.message>
        - name: author
          type: String
          value: <+trigger.payload.head_commit.author.name>

---
# Trigger 3: Release Publish - Deploy to Production
# Deploys to production when a new release is published
# Only triggers for semantic version tags (v1.0.0, v2.1.3, etc.)

trigger:
  identifier: production_release_trigger
  name: Production Release Trigger
  orgIdentifier: my_org
  projectIdentifier: my_project
  pipelineIdentifier: deploy_pipeline
  description: "Deploy to production when a release is published"
  enabled: true
  tags:
    type: cd
    environment: production
    event: release
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Release
        spec:
          connectorRef: github_connector
          repoName: my-org/my-app
          actions:
            - Publish
          payloadConditions:
            - key: <+trigger.payload.release.tag_name>
              operator: Regex
              value: ^v[0-9]+\.[0-9]+\.[0-9]+$
            - key: <+trigger.payload.release.prerelease>
              operator: Equals
              value: "false"
          headerConditions: []
          jexlCondition: ""
  inputYaml: |
    pipeline:
      variables:
        - name: environment
          type: String
          value: production
        - name: version
          type: String
          value: <+trigger.payload.release.tag_name>
        - name: release_name
          type: String
          value: <+trigger.payload.release.name>
        - name: release_url
          type: String
          value: <+trigger.payload.release.html_url>

---
# Trigger 4: Nightly Build (Scheduled)
# Runs a full build and test suite every night at 2 AM UTC

trigger:
  identifier: nightly_build_trigger
  name: Nightly Build Trigger
  orgIdentifier: my_org
  projectIdentifier: my_project
  pipelineIdentifier: ci_pipeline
  description: "Run full test suite every night at 2 AM UTC"
  enabled: true
  tags:
    type: ci
    schedule: nightly
  source:
    type: Scheduled
    spec:
      type: Cron
      spec:
        expression: "0 2 * * *"
        timezone: "UTC"
  inputYaml: |
    pipeline:
      variables:
        - name: full_test_suite
          type: String
          value: "true"
        - name: trigger_type
          type: String
          value: "scheduled"

---
# Trigger 5: Docker Image Update - Deploy on New Image
# Automatically deploys when a new Docker image is pushed to ECR

trigger:
  identifier: ecr_image_trigger
  name: ECR Image Deploy Trigger
  orgIdentifier: my_org
  projectIdentifier: my_project
  pipelineIdentifier: deploy_pipeline
  description: "Deploy when new image is pushed to ECR with release tag"
  enabled: true
  tags:
    type: cd
    artifact: ecr
  source:
    type: Artifact
    pollInterval: "5m"
    spec:
      type: Ecr
      spec:
        connectorRef: aws_connector
        region: us-east-1
        registryId: "123456789012"
        imagePath: my-app
        tag: <+trigger.artifact.build>
        eventConditions: []
        metaDataConditions:
          - key: <+trigger.artifact.metadata.tag>
            operator: Regex
            value: ^v[0-9]+\.[0-9]+\.[0-9]+$
        jexlCondition: ""
      stageIdentifier: deploy_stage
      artifactRef: primary
  inputYaml: |
    pipeline:
      variables:
        - name: environment
          type: String
          value: staging
        - name: image_tag
          type: String
          value: <+trigger.artifact.build>
